Proof GIMBAL_LOCK_AVOIDANCE #585
chrislgarry/Apollo-11 pull request #700
Opened 2020-09-15 17:00 UTC by rcornbtree

Full file checked:

- Line 63: Unsure if period or commas -- left unchanged from scan

2020-09-18 22:27 UTC, wopian requested changes
PR additions themselves are good, just one missed transcription error.

2020-09-18 22:27 UTC, wopian commented on Luminary099/GIMBAL_LOCK_AVOIDANCE.agc
>  # THE FOUR SELECTABLE FREE FALL MANEUVER RATES SELECTED BY
Line below this doesn't have spaces between the numbers.

R0030 https://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0364.jpg

```diff
- # LOADING RATEINDX WITH 0, 2, 4, 6, RESPECTIVELY
+ # LOADING RATEINDX WITH 0,2,4,6, RESPECTIVELY
```

2020-09-19 19:27 UTC, rcornbtree commented
Good catch, removed those spaces -- thanks!

2020-09-19 21:16 UTC, wopian approved these changes

2020-09-19 21:16 UTC, merged

2020-09-19 21:17 UTC, wopian commented
Thank you for contributing 🙂