Proof GROUND_TRACKING_DETERMINATION_PROGRAM #586
chrislgarry/Apollo-11 pull request #701
Opened 2020-09-15 21:30 UTC by rcornbtree

Full file checked, another eye might be nice on:

- Generally wonky indents + line breaks across first page
- Line 76: Underscore used where there should be a negative
- Line 115: Possible that '1ST' is typed 'IST', unsure
- Line 161: Unsure what character is used, left unchanged from '+'

2020-09-18 23:22 UTC, wopian requested changes
Thank you for opening your first proofing PR for Apollo 11 🎉 

I've gone through and double checked the PR changes, marked any missing transcription errors as commit suggestions (some were out of range of touched lines so was only able to create comments showing the changes needed) and hopefully answered your questions.

> Generally wonky indents + line breaks across first page

If this is rereferring to the AXO/AYO table, I've fixed the alignment issues for you. 

Commented tables will always be a bit wider or narrower as we're working with an additional `# ` at the front of every comment line that the source files do not need to indicate comments.

This sometimes forces an additional tab to keep the vertical alignment as it effectively turns the first 8-character wide tab into 6 usable characters, so what would fit inside one tab column now takes up two tab columns.
- `504LM	_2` is 8 characters wide
- `# 504LM	_2` is 10 characters wide (consumes 2 characters of the next tab column)

> Line 76: Underscore used where there should be a negative

Typos present need to remain as they are in the scans - so here, we have to keep the underscore instead of a minus-dash.

> Line 115: Possible that '1ST' is typed 'IST', unsure

I've checked the scans and they did indeed type `IST` (capital `i`) instead of `1ST`

![image](https://user-images.githubusercontent.com/3440094/93652064-99320d80-fa0b-11ea-9c3b-dda94dadbe7f.png)

> Line 161: Unsure what character is used, left unchanged from '+'

This looks like an ampersand (&) with an older (but still used) letterform (🙲)

![image](https://user-images.githubusercontent.com/3440094/93652110-c4b4f800-fa0b-11ea-9a99-7336a63bac54.png)

I've cross-referenced it with other ampersand occurrences in the transcriptions and the letterform matches the scans (and appear to be proper usage of an ampersand)

R0093 and R0095 https://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0003.jpg

![image](https://user-images.githubusercontent.com/3440094/93652213-2ffeca00-fa0c-11ea-85fd-59252032dcb4.png)

2020-09-19 19:37 UTC, rcornbtree commented
Thanks for the in-depth review and for making most of those changes ahead of me, I'll keep a better eye on leaving spacing + characters exactly as they are in future scans.

I've pushed another commit to fix the three comments that were out of scope from other changes, let me know if that's the right way to handle it -- open-source work on GitHub is a bit new to me still. Thanks!

2020-09-20 21:41 UTC, wopian approved these changes

2020-09-20 21:41 UTC, wopian commented on Luminary099/GROUND_TRACKING_DETERMINATION_PROGRAM.agc
> +			+2		# ZERO--THIS VEHICLE (LM)
```suggestion
			+2		# ZERO--THIS VEHICLE(LM)
```

2020-09-20 21:41 UTC, wopian commented on Luminary099/GROUND_TRACKING_DETERMINATION_PROGRAM.agc
> +			VINTFLAG	# ONE--OTHER VEHICLE (CM)
```suggestion
			VINTFLAG	# ONE--OTHER VEHICLE(CM)
```

2020-09-20 21:43 UTC, merged

2020-09-20 21:44 UTC, wopian commented
> I've pushed another commit to fix the three comments that were out of scope from other changes, let me know if that's the right way to handle it -- open-source work on GitHub is a bit new to me still. Thanks!

That's the correct way to handle it 👍