Proof IMU_COMPENSATION_PACKAGE #587
chrislgarry/Apollo-11 pull request #707
Opened 2020-10-03 22:18 UTC by ShadowMitia

Closes #587.

2020-10-07 22:37 UTC, wopian requested changes
Review up to page 332. Pages 333 to 337 have not been reviewed yet.

I've checked and committed several suggestions for you. Some requested changes were outside of range that you'll need to commit those yourself manually.

This file really lends itself to using rulers in a code editor as the file is filled with characters that hug the right-most column of the page (column 81 - technically 80 without the `#`). If you're using Visual Studio Code, this is a good ruler to use in `settings.json` and can be achieved in all other editors:

```json
"editor.rulers": [8, 16, 24, 32, 40, 42, 81, 82]
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		DCS	DELVY		# 	(PIPA PULSES) X 2(+14)
4 lines above, replace with:

```diff
-# (GYRO PULSES)/(PIPA PULSE) X 2(-6)		*
+# (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		DCS	DELVY		# 	(PIPA PULSES) X 2(+14)
3 lines above, replace with:

```diff
-# -(ADIAX)(PIPAX)	   (GYRO PULSES) X 2(+14)
+# -(ADIAX)(PIPAX)   (GYRO PULSES) X 2(+14)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		DCS	DELVY		# 	(PIPA PULSES) X 2(+14)
```suggestion
		DCS	DELVY		# (PIPA PULSES) X 2(+14)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		CS	ADSRAX		# 	(GYRO PULSES)/(PIPA PULSE) X 2(-6)	*
```suggestion
		CS	ADSRAX		# (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
> +		TC	GCOMPSUB	# 	+(ADSRAX)(PIPAY)   (GYRO PULSES) X 2(+14)
```suggestion
		TC	GCOMPSUB	# +(ADSRAX)(PIPAY)  (GYRO PULSES) X 2(+14)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		EXTEND			# ***
```suggestion
#		EXTEND		  # ***
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
> +#		DCS	DELVZ		# ***	(PIPA PULSES) X 2(+14)
```suggestion
#		DCS	DELVZ	  # ***   (PIPA PULSES) X 2(+14)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DXCH	MPAC		# ***
```suggestion
#		DXCH	MPAC	  # ***
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		CA	ADOAX		# ***	(GYRO PULSES)/(PIPA PULSE) X 2(-6)	*
```suggestion
#		CA	ADOAX	  # ***   (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		TC	GCOMPSUB	# ***	-(ADOAX)(PIPAZ)	   (GYRO PULSES) X 2(+14)
```suggestion
#		TC	GCOMPSUB  # ***   -(ADOAX)(PIPAZ)   (GYRO PULSES) X 2(+14)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DCS	DELVX		# ***	(PIPA PULSES) X 2(+14)
Line 145 (above), replace with:

```diff
-# (GYRO PULSES)/(PIPA PULSE) X 2(-6)		*
+# (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DCS	DELVX		# ***	(PIPA PULSES) X 2(+14)
Line 146 (above), replace with:

```diff
-# -(ADIAY)(PIPAY)	   (GYRO PULSES) X 2(+14)
+# -(ADIAY)(PIPAY)   (GYRO PULSES) X 2(+14)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DCS	DELVX		# ***	(PIPA PULSES) X 2(+14)
Line 151 (above), replace with:

```diff
-# (GYRO PULSES)/(PIPA PULSE) X 2(-6)		*
+# (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DCS	DELVX		# ***	(PIPA PULSES) X 2(+14)
Line 152 (above), replace with:

```diff
-# +(ADSRAY)(PIPAZ)      	(GYRO PULSES) X 2(+14)
+# +(ADSRAY)(PIPAZ)  (GYRO PULSES) X 2(+14)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DCS	DELVX		# ***	(PIPA PULSES) X 2(+14)
1 line above, replace with:

```diff
-#		EXTEND			# ***
+#		EXTEND		  # ***

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DCS	DELVX		# ***	(PIPA PULSES) X 2(+14)
```suggestion
#		DCS	DELVX	  # ***   (PIPA PULSES) X 2(+14)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		DXCH	MPAC		# ***
```suggestion
#		DXCH	MPAC	  # ***
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  #		CA	ADOAY		# ***	(GYRO PULSES)/(PIPA PULSE) X 2(-6)	*
```suggestion
#		CA	ADOAY	  # ***   (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
> +#		TC	GCOMPSUB	# ***	-(ADOAY)(PIPAX)   (GYRO PULSES) X 2(+14)
```suggestion
#		TC	GCOMPSUB  # ***   -(ADOAY)(PIPAX)   (GYRO PULSES) X 2(+14)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
Line 167 (below), replace with:

```diff
-# (GYRO PULSES)/(PIPA PULSE) X 2(-6)		*
+# (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
Line 169 (below), replace with:

```diff
-# -(ADSRAZ)(PIPAY)	  (GYRO PULSES) X 2(+14)
+# -(ADSRAZ)(PIPAY)  (GYRO PULSES) X 2(+14)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
Line 174 (below), replace with:

```diff
-# (GYRO PULSES)/(PIPA PULSE) X 2(-6)		*
+# (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
Line 175 (below), replace with:

```diff
-# -(ADIAZ)(PIPAZ)	   (GYRO PULSES) X 2(+14)
+# -(ADIAZ)(PIPAZ)   (GYRO PULSES) X 2(+14)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
Lines 177-181 (below), replace with:

```diff
-#		EXTEND			# ***
-#		DCS	DELVX		# ***	(PIPA PULSE) X 2(+14)
-#		DXCH	MPAC		# ***
-#		CS	ADOAZ		# ***	(GYRO PULSES)/(PIPA PULSE) X 2(-6)	*
-#		TC	GCOMPSUB	# ***	+(ADOAZ)(PIPAX)	   (GYRO PULSES) X 2(+14)
+#		EXTEND		  # ***   
+#		DCS	DELVX	  # ***   (PIPA PULSE) X 2(+14)
+#		DXCH	MPAC	  # ***   
+#		CS	ADOAZ	  # ***   (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *
+#		TC	GCOMPSUB  # ***   +(ADOAZ)(PIPAX)   (GYRO PULSES) X 2(+14)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 188 (above), replace with:

```diff
-# (GYRO PULSES)/(PIPA PULSE) X 2(-6)		*
+# (GYRO PULSES)/(PIPA PULSE) X 2(-6)	 *
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 189 (above), replace with:

```diff
-# NOW = (GYRO PULSES) X 2(+8)			*
+# NOW = (GYRO PULSES) X 2(+8)		 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 196 (above), replace with:

```diff
-# NOW = (GYRO PULSES) X 2(+8)			*
+# NOW = (GYRO PULSES) X 2(+8)		 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 198 (above), `-` instead of `--`

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 200 (above), replace with:

```diff
-# SCALE 2(+6)	SHIFT RIGHT 6			*
+# SCALE 2(+6)	SHIFT RIGHT 6		 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 202 (above), replace with:

```diff
-# HI(ADIA)(PIPAI) OR HI(ADSRA)(PIPAI)
+# HI(ADIA)(PIPAI)  OR  HI(ADSRA)(PIPAI)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 204 (above), `-` instead of `--`

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 206 (above), replace with:

```diff
-# SCALE 2(+6)	SHIFT RIGHT 6			*
+# SCALE 2(+6)	SHIFT RIGHT 6		 *

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		QXCH	BUF 	+1
Line 210 (above), replace with:

```diff
-# (ADIA)(PIPAI) OR (ADSRA)(PIPAI)
+# (ADIA)(PIPAI)  OR  (ADSRA)(PIPAI)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
> +		MP	1/PIPADT	# (CS) X 2(+8)	NOW (GYRO PULSES) X 2(+3)
```suggestion
		MP	1/PIPADT	# (CS) X 2(+8)	 NOW (GYRO PULSES) X 2(+3)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		MP	BIT4		# SCALE 2(+11)	SHIFT RIGHT 11
```suggestion
		MP	BIT4		# SCALE 2(+11)	   SHIFT RIGHT 11
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		DAS	GCOMP		# HI(NBD)(DELTAT)	(GYRO PULSES) X 2(+14)
```suggestion
		DAS	GCOMP		# HI(NBD)(DELTAT)   (GYRO PULSES) X 2(+14)
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		MP	BIT4		# SCALE 2(+11)		SHIFT RIGHT 11
```suggestion
		MP	BIT4		# SCALE 2(+11)	   SHIFT RIGHT 11
```

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		TS	L
Line 232 (below), replace with:

```diff
-# (NBD)(DELTAT)		(GYRO PULSES) X 2(+14)
+# (NBD)(DELTAT)	    (GYRO PULSES) X 2(+14)

2020-10-07 22:37 UTC, wopian commented on Luminary099/IMU_COMPENSATION_PACKAGE.agc
>  		TS	L
Line 244 (below), replace `--` with `-`

2020-10-13 20:54 UTC, ShadowMitia commented
Sorry about the poor commit, I guess I didn't read how to contribute well enough...

I should've applied all of your changes, and I redid a proofread and should've aligned everything correctly now.

2020-10-14 16:55 UTC, wopian approved these changes

2020-10-14 16:55 UTC, merged

2020-10-14 17:08 UTC, wopian commented
> Sorry about the poor commit, I guess I didn't read how to contribute well enough...

No worries, you did well for a first-time proof read with spotting most of the typos

2020-10-14 17:34 UTC, ShadowMitia commented
Thanks!