Proof INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.acg #592
chrislgarry/Apollo-11 pull request #708
Opened 2020-10-04 05:58 UTC by panoreak

Proofread INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.acg for issue #592.

2020-10-08 21:31 UTC, wopian requested changes
Thank you for the PR!

I've added some code suggestions for some missed typos.

Looking at the source scans compared to the files, I feel the entire `CHANNEL` and `BIT n` columns need adjusting.
![image](https://user-images.githubusercontent.com/3440094/95515509-a5c7d700-09b5-11eb-99af-2a7b891c93ba.png)
1. Replace the space character before each `CHANNEL` with a tab, i.e 
    ```
    # 	CHANNEL 12	CHAN12;
    #[tab]CHANNEL 12[tab]CHAN12;
    ```
    instead of 
    ```
    # CHANNEL 12	CHAN12;
    #[space]CHANNEL 12[tab]CHAN12;
    ```

2. Replace the double tab before `BIT n` with a tab and 2 spaces, i.e (BIT 10+ only needs 1 tab after)
    ```
    #	  BIT 1		ZERO
    #[tab][space][space]BIT 1[tab][tab]ZERO
    #	  BIT 10	ZERO
    #[tab][space][space]BIT 10[tab]ZERO
    ```
    instead of 
    ```
    #		BIT 1		ZERO
    #[tab][tab]BIT 1[tab][tab]ZERO
    ```

This would result in the code looking like the following:
![image](https://user-images.githubusercontent.com/3440094/95515692-f2abad80-09b5-11eb-8b37-13f1c455bcf9.png)

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
>  # CHANNEL 31	INPUT CHANNEL; BITS ASSOCIATED WITH THE ATTITUDE CONTROLLER, TRANSLATIONAL CONTROLLER,
```suggestion
# CHANNEL 31	INPUT CHANNEL; BITS ASSOCIATED WITH THE ATTITUDE  CONTROLLER, TRANSLATIONAL CONTROLLER,
```

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
>  #				ALSO POSITIVE ELEVATION CHANGE FOR LANDING POINT DESIGNATOR
```suggestion
#				ALSO POSITIVE ELEVATION CHANGE FOR LANDING POINT  DESIGNATOR
```

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
>  # CHANNEL 32	INPUT CHANNEL.
```suggestion
# CHANNEL 32	   INPUT CHANNEL.
```

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
>  #
![image](https://user-images.githubusercontent.com/3440094/95513662-97c48700-09b2-11eb-8d1b-293a54e99357.png)
3 extra spaces before description on all lines except `INDICATES`

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
Line below, 

- `CHAN33;` instead of `CHAN33:` (semicolon)
- Single space before `BITS 15-11` instead of double space

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
>  #		BIT 14		WARNING OF REPEATED ALARMS: RESTART, COUNTER FAIL, VOLTAGE FAIL, AND SCALAR DOUBLE.
```suggestion
#		BIT 14		WARNING OF REPEATED ALARMS: RESTART,COUNTER FAIL, VOLTAGE FAIL,AND SCALAR DOUBLE.
```

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
> +# CHANNEL 34	DNT M1: OUTPUT CHANNEL; DOWNLINK 1 FIRST OF TWO WORDS SERIALIZATION.
```suggestion
# CHANNEL 34	DNT M1; OUTPUT CHANNEL; DOWNLINK 1  FIRST OF TWO WORDS SERIALIZATION.
```

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
> +# CHANNEL 35	DNT M2: OUTPUT CHANNEL DOWNLINK 2 SOCOND OF TWO WORDS SERIALIZATION.
```suggestion
# CHANNEL 35	DNT M2; OUTPUT CHANNEL DOWNLINK 2 SOCOND OF TWO   WORDS SERIALIZATION.
```

2020-10-08 21:31 UTC, wopian commented on Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc
> +# *** CHANNEL DESCRIPTIONSF WORDS ARE ALLOCATED IN ERASABLE ASSIGNMENTS ***
```suggestion
# ***	CHANNEL DESCRIPTIONSF WORDS ARE ALLOCATED IN ERASABLE ASSIGNMENTS ***
```

2020-10-11 02:00 UTC, wopian approved these changes
Thank you for helping proof! 🎉

2020-10-11 02:01 UTC, merged

2020-10-11 16:22 UTC, panoreak commented
> Thank you for helping proof! 🎉

Woohoo! Glad I could help ☺️