Update P30_P37.agc
chrislgarry/Apollo-11 pull request #709
Opened 2020-10-04 10:42 UTC by Lifeindeath

Fixing issue #613

2020-10-08 21:54 UTC, wopian requested changes
Thank you for opening this PR. I've added some code suggestions for missed typos (or accidental replacement of correct characters - mainly badly printed commas that plague these scans).

Two of these are out of range of the code suggestions feature and will need to be committed manually by you.

- https://github.com/chrislgarry/Apollo-11/pull/709/files#r502030829
- https://github.com/chrislgarry/Apollo-11/pull/709/files#r502033150

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  #
```suggestion
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +#	DISPLAY TIME TO GO.  APOGEE, PERIGEE, DELV(MAG), MGA AT IGN
Badly printed comma
```suggestion
#	DISPLAY TIME TO GO, APOGEE, PERIGEE, DELV(MAG), MGA AT IGN
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +		TC	VNPOOH		#	REDISPLAY ON RECYCLE
```suggestion
		TC	VNPOOH		#     REDISPLAY ON RECYCLE
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +PARAM30		CAF	V06N42		# DISPLAY APOGEE, PERIGEE, DELTA V
![image](https://user-images.githubusercontent.com/3440094/95516700-8cc02580-09b7-11eb-8f76-e3f42223957a.png)
```suggestion
PARAM30		CAF	V06N42		# DISPLAY APOGEE,PERIGEE ,DELTA V
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +			REVN1645	# TRKMKCNT, T60, +MGA DISPLAY
```suggestion
			REVN1645	# TRKMKCNT, T60, +MGA  DISPLAY
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  #	BASED ON STORED TARGET PARAMETERS (R OF IGNITION (RTIG), V OF
```suggestion
#	BASED ON STORED TARGET PARAMETERS(R OF IGNITION(RTIG),V OF
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +#	IGNITION (VTIG), TIME OF IGNITION (TIG)).  COMPUTE PERIGEE ALTITUDE
```suggestion
#	IGNITION(VTIG),TIME OF IGNITION (TIG)),COMPUTE PERIGEE ALTITUDE
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  #	APOGEE ALTITUDE AND DELTAV REQUIRED (DELVSIN).
```suggestion
#	APOGEE ALTITUDE AND DELTAV REQUIRED(DELVSIN).
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  #
```suggestion
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  #
```suggestion
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  # CALLING SEQUENCE
Line 105, no empty line before `NORMAL EXIT MODE`

Line 108, no empty line before `SUBROUTINES CALLED`

Line 112, no empty line before `ALARM OR ABORT`

Line 115, no empty line before `ERASABLE INITIALIZATION`

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +#	PDL 4D		APOGEE ALTITUDE		DP 	B+29 M, B+27 METERS.
```suggestion
#	PDL 4D		APOGEE ALTITUDE		DP 	B+29 M ,  B+27 METERS.
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +#	PDL 8D		PERIGEE ALTITUDE	DP 	B+29 M, B+27 METERS.
```suggestion
#	PDL 8D		PERIGEE ALTITUDE	DP 	B+29 M ,  B+27 METERS.
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +#		QPRET.MPAC
Badly printed comma
```suggestion
#		QPRET,MPAC
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +		VLOAD	SXA.2
```suggestion
		VLOAD	SXA,2
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +		SETPD	SXA.1
```suggestion
		SETPD	SXA,1
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  		PUSH	VXV		# YRF/LV PDL 0 SCALED AT 2
```suggestion
		PUSH	VXV		# YRF/LV PDL 0  SCALED AT 2
```

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  		PUSH	VXV		# YRF/LV PDL 0 SCALED AT 2
Line 166 (YRF/LV), triple space before `SCALED` instead of single

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
>  			SHIFTR1		# RESCALE IF NEEDED
Line 184 (`PERIGEE ALT`), comma after `METERS`

2020-10-08 21:54 UTC, wopian commented on Luminary099/P30_P37.agc
> +		STCALL	HAPO		# APOGEE ALT 2(29) METERS, FOR DISPLAY
```suggestion
		STCALL	HAPO		# APOGEE  ALT 2(29) METERS, FOR DISPLAY
```

2020-10-27 02:45 UTC, wopian commented
Hey @Lifeindeath, this PR is waiting on 2 changes I couldn't commit for you that are linked in https://github.com/chrislgarry/Apollo-11/pull/709#pullrequestreview-505184446 (or above).

Once those changes have been committed, this is good to be merged 👍

2020-12-26 06:36 UTC, chrislgarry commented
@Lifeindeath if you're still up for it, this can be merged once you commit the changes @wopian shared in the comments. Thanks!

2021-01-06 19:31 UTC, wopian approved these changes

2021-01-06 19:32 UTC, wopian commented
Thank you @Lifeindeath for proofing this file 👍

2021-01-06 19:32 UTC, merged