Add Lithuanian Contributing file
chrislgarry/Apollo-11 pull request #728
Opened 2020-10-07 19:02 UTC by GintasS

2020-10-09 19:07 UTC, wopian commented
The `Ką man reikia patikrinti?` section was recently updated and needs re-translating to match the current translation. 

You can find the changes made to the English CONTRIBUTING at https://github.com/chrislgarry/Apollo-11/commit/16aa2154b23dda648a2ab568734e11627af8448b

2020-10-09 19:49 UTC, GintasS commented
> The `Ką man reikia patikrinti?` section was recently updated and needs re-translating to match the current translation.
> 
> You can find the changes made to the English CONTRIBUTING at [16aa215](https://github.com/chrislgarry/Apollo-11/commit/16aa2154b23dda648a2ab568734e11627af8448b)

Will change.

2020-10-10 09:36 UTC, GintasS commented
Updated to match the changes.

2020-10-10 15:43 UTC, wopian commented
Thank you :)

2020-10-10 15:45 UTC, wopian requested changes

2020-10-10 15:45 UTC, wopian commented on CONTRIBUTING.lt.md
> +**Lietuvių**,
Alphabetical order (After Kurdi)

2020-10-11 12:36 UTC, GintasS commented on CONTRIBUTING.lt.md
> +**Lietuvių**,
Fixed.

2020-10-13 00:24 UTC, wopian approved these changes

2020-10-13 00:31 UTC, merged