Proof Luminary099/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc page 392
chrislgarry/Apollo-11 pull request #931
Opened 2024-12-31 01:32 UTC by lurch

See https://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0392.jpg

I spotted the "PACE NUMBERS" typo on https://www.ibiblio.org/apollo/listings/Luminary099/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc.html so decided to fix it here, and spotted a couple of other typos whilst I was at it. I've **only** checked page 392.

2024-12-31 19:09 UTC, wopian requested changes

2024-12-31 19:09 UTC, wopian commented on Luminary099/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc
> +#			COMBINATION OF THE DISPLAY REGISTERS R1. R2. R3.
These are commas in the original scans

![image](https://github.com/user-attachments/assets/f552003d-6251-43af-bdfe-d15ee8a91866)

2025-01-01 16:23 UTC, lurch commented on Luminary099/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc
> +#			COMBINATION OF THE DISPLAY REGISTERS R1. R2. R3.
Fixed :+1:  (I guess it's hard to tell the difference between commas and full-stops in the scans :confused: )

2025-01-04 19:53 UTC, wopian commented on Luminary099/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc
> +#			COMBINATION OF THE DISPLAY REGISTERS R1. R2. R3.
Yeah, the printing of some characters is not the best in many pages - having the images on higher than 100% zoom is often the best way to verify

2025-01-04 19:53 UTC, wopian approved these changes

2025-01-04 19:53 UTC, merged